default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aceleracao_dio_service_orders_development

test:
  <<: *default
  database: aceleracao_dio_service_orders_test

production:
  <<: *default
  database: aceleracao_dio_service_orders_production
  username: service_orders
  password: <%= ENV['SERVICE_ORDERS_DATABASE_PASSWORD'] %>
