source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'bootsnap', '>= 1.4.4', require: false
gem 'bunny', '2.17.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.1'

group :development, :test do
  gem 'dotenv-rails', '2.7.6'
  gem 'pry-byebug', '3.9.0'
  gem 'pry-rails', '0.3.9'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring', '2.1.1'
end